id: P000035
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །སྔོན་འགྲོ་བློ་ལྡོག་རྣམ་བཞིའི་ཟིན་ཐུན་མདོར་བསྡུས་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། མཚུངས་མེད་གྲུབ་པའི་དབང་ཕྱུག་ཤཱཀྱ་ཤྲཱི་ཛྙཱ་ནའི་རྒྱལ་སྲས་འཕགས་མཆོག་རྡོ་རྗེ་མཆོག
    །
  layers:
  - book_title
  - author
  - quotation
  id: KS-SP-01
web_metadata:
  title:
    en: Notes on the Four Thoughts That Turn the Mind
    bo: སྔོན་འགྲོ་བློ་ལྡོག་རྣམ་བཞིའི་ཟིན་ཐུན་མདོར་བསྡུས་བཞུགས་སོ།།
  collection:
    en: Se Phakchok Series–  Book 1
    bo: སྲས་འཕགས་མཆོག།–  དེབ། ༡
  author:
    en: Authors:Phakchok Dorje
    bo: འཕགས་མཆོག་རྡོ་རྗེ།
  pusblisher:
    en: Gautam Buddha Vihara
    bo: དོན་བརྒྱུད་དཔལ་ལྡན་འབྲུག་པ།
  sku: KS-SP-01
  category:
    en: Preliminary Practices
    bo: སྔོན་འགྲོ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KS-SP-01.epub
  description:
    en: ''
    bo: ''
